homePage:
    path:      /home/
    defaults:  { _controller: AppBundle:Default:index }
signIn:
    path:      /signIn/
    defaults:  { _controller: AppBundle:Default:signIn }
signIn_process:
    path:      /signIn_process/
    defaults:  { _controller: AppBundle:Default:signIn_process }
signOut:
    path:      /signOut/
    defaults:  { _controller: AppBundle:Default:signOut }
browsePrints:
    path:      /browsePrints/
    defaults:  { _controller: AppBundle:Default:browsePrints }
viewPrints:
    path:      /viewPrints/
    defaults:  { _controller: AppBundle:Default:viewPrints }
viewAtrist:
    path:      /viewAtrist/
    defaults:  { _controller: AppBundle:Default:viewAtrist }
addCart:
    path:      /addCart/
    defaults:  { _controller: AppBundle:Default:addCart }
viewCart:
    path:      /viewCart/
    defaults:  { _controller: AppBundle:Default:viewCart }
checkOut:
    path:      /checkOut/
    defaults:  { _controller: AppBundle:Default:checkOut }
register:
    path:      /register/
    defaults:  { _controller: AppBundle:Default:register }
register_process:
    path:      /register_process/
    defaults:  { _controller: AppBundle:Default:register_process }